language: python
python:
  - "3.9"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: make setup
# # command to run tests
script: xvfb-run make test
